stages:
- name: build & publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.heroku.com/mundi-alert/web
      pushRemote: true
      registry: registry.heroku.com
- name: slack notify
  steps:
  - runScriptConfig:
      image: technosophos/slack-notify
      shellScript: echo Go!
    env:
      SLACK_COLOR: '#0000ff'
      SLACK_MESSAGE: 'Your app has been published and deployed! Congrats! :sparkles:'
      SLACK_TITLE: Rancher Pipelines
      SLACK_USERNAME: Sabrino
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
    when:
      branch:
        include:
        - master
timeout: 60
